### ISSUE TITLE
Crashed Website on install

### ISSUE THREAD

**Issue by plutocrat** [excelerus/wp-org-shipping-rates-for-hk-post#1]
Wordpress was inaccessible directly after hitting activate on your plugin. Had to disable it using 
wp-cli plugin delete --skip-plugins

Seems the problem is the file in the includes directory. 
class-wc-hk-post-shipping-method.php is referenced in the code, yet the file in the plugin zip is class-hk-post.php
Thought I'd let you know.

**Comment by plutocrat** [comment]
Creating a symlink from class-wc-hk-post-shipping-method.php to class-hk-post.php fixes the crash. However the plugin seems not to work. There is no indication of its presence in Woocommerce Shipping settings once its enabled.

**Comment by rangatia** [comment]
@plutocrat 
sorry missed this earlier.

just had a new release (1.1) with additional features and fixing other issues.

do have a look and please post feedback and suggestions in the plugin support 

thanks
